services:
  frontend:
    build: ./student-list
    container_name: react-ui
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-network
  
  backend:
    build: ./nodejs-crud-student/nodejs-crud-student
    container_name: node-api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - mern-network
  
  database:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d/
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge